import { Command } from 'commander';
import {
  GoogleGenAI,
  type FunctionDeclaration,
  type Part,
} from '@google/genai';
import { getCurrentSession, PROVIDERS_TYPES } from '../utils/share';
import OpenAI from 'openai';
import Anthropic from '@anthropic-ai/sdk';
import readline from 'readline';
import { getAllToolsOfProviders } from '../utils/providersToolAdapter';
import {
  bashTool,
  writeFileTool,
  readFileTool,
  grepSearchTool,
  findFilesTool,
  gitTool,
  WorkFlowStep,
} from '../utils/toolsDefinition';
import {
  createHooks,
  addPreHook,
  addPostHook,
  firePreHooks,
  firePostHooks,
  type Hooks,
  type HookContext,
} from '../utils/lifecycleHooks';
import { intializeSubAgents } from '../utils/sunagents';
import { log } from 'console';

// Skills generated by skill_maker are stored here and injected into every subagent
let generatedSkills = '';

type QueueItem = {
  toolId: string;
  toolName: string;
  args: Record<string, unknown>;
  status: 'pending' | 'completed';
};
async function askPermission(
  toolName: string,
  args: Record<string, unknown>,
): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const cwd = process.cwd();
  const line = '─'.repeat(60);

  const argLines = Object.entries(args)
    .map(([k, v]) => `  │  ${k}: ${String(v)}`)
    .join('\n');

  const banner =
    `\n${line}\n` +
    `  Calling  ${toolName}\n` +
    `  │  path: ${cwd}\n` +
    `${argLines}\n` +
    `${line}`;

  return new Promise((resolve) => {
    rl.question(`${banner}\n  Allow? (y/n): `, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase() === 'y');
    });
  });
}

export async function dispatchTool(
  name: string,
  args: Record<string, unknown>,
  hooks: Hooks,
): Promise<string> {
  const context: HookContext = { tool: { name, args } };

  const decision = await firePreHooks(hooks, context);
  if (decision === 'deny') {
    return JSON.stringify({
      success: false,
      errorMessage: 'Blocked by pre-hook.',
    });
  }

  let result: unknown;
  if (name === 'zsh') {
    result = await bashTool(args.comand as string);
  } else if (name === 'file_write') {
    result = await writeFileTool(
      args.fileName as string,
      args.content as string,
    );
  } else if (name === 'read_file') {
    result = await readFileTool(args.fileName as string);
  } else if (name === 'grep_search') {
    result = await grepSearchTool(
      args.pattern as string,
      args.directory as string,
      args.fileGlob as string | undefined,
    );
  } else if (name === 'find_files') {
    result = await findFilesTool(
      args.directory as string,
      args.namePattern as string,
    );
  } else if (name === 'git') {
    result = await gitTool(args.gitCommand as string, args.repoPath as string);
  } else if (name === 'create_a_subagent') {
    const basePrompt = args.systemPrompt as string;
    const enrichedPrompt = generatedSkills
      ? `## SKILLS & BEST PRACTICES\n${generatedSkills}\n\n---\n\n${basePrompt}`
      : basePrompt;
    result = await intializeSubAgents(
      args.provider as PROVIDERS_TYPES,
      args.query as string,
      enrichedPrompt,
      hooks,
    );
  } else if (name === 'plan_maker') {
    console.log(`\n  [PLAN] plan_maker called -- handing off to ToolSchedular`);
    result = await toolSchedular(hooks, args.steps as WorkFlowStep[]);
  } else if (name === 'skill_maker') {
    generatedSkills = (args.skills as string) ?? '';
    console.log('[SKILL_MAKER] Skills stored, will be injected into subagents.');
    result = { success: true, data: 'Skills stored.' };
  }
  else {
    result = { success: false, errorMessage: `Unknown tool: ${name}` };
  }

  context.result = result;
  await firePostHooks(hooks, context);

  return JSON.stringify(result);
}

async function toolSchedular(
  hooks: Hooks,
  workFlowSteps: WorkFlowStep[],
): Promise<Part[]> {
  const toolResults: Part[] = [];
  let waitingQueue: QueueItem[] = [];
  const readyQueue: QueueItem[] = [];
  const completedSet = new Set<string>();

  const line = '='.repeat(55);
  const total = workFlowSteps.length;

  console.log(`\n${line}`);
  console.log(`  PLAN STARTED  (${total} jobs to do)`);
  console.log(line);
  for (let i = 0; i < workFlowSteps.length; i++) {
    const step = workFlowSteps[i];
    const deps =
      step.dependsOn.length > 0
        ? `  <-- needs: ${step.dependsOn.join(', ')}`
        : '  <-- can start right away';
    console.log(`  Job ${i + 1}: ${step.toolName} (id: ${step.id})${deps}`);
  }
  console.log(line);

  for (const step of workFlowSteps) {
    const item: QueueItem = {
      toolId: step.id,
      toolName: step.toolName,
      args: step.args,
      status: 'pending',
    };
    if (step.dependsOn.length === 0) {
      readyQueue.push(item);
    } else {
      waitingQueue.push(item);
    }
  }

  async function runWorker(): Promise<void> {
    const tool = readyQueue.shift();
    if (!tool) return;

    const result = await dispatchTool(tool.toolName, tool.args, hooks);

    completedSet.add(tool.toolId);
    console.log(
      `  FINISHED: ${tool.toolName} (${tool.toolId})  [${completedSet.size} of ${total} done]`,
    );

    toolResults.push({
      functionResponse: { name: tool.toolName, response: { result } },
    });

    const nowReady = waitingQueue.filter((waiting) => {
      const step = workFlowSteps.find((s) => s.id === waiting.toolId);
      return step?.dependsOn.every((depId) => completedSet.has(depId)) ?? false;
    });

    for (const task of nowReady) {
      waitingQueue = waitingQueue.filter((q) => q.toolId !== task.toolId);
      readyQueue.push(task);
      console.log(
        `  READY NOW: ${task.toolName} (${task.toolId}) -- its dependencies are done`,
      );
    }

    return runWorker();
  }

  while (readyQueue.length > 0 || waitingQueue.length > 0) {
    const poolSize = Math.min(readyQueue.length, 5);
    if (poolSize === 0) break;
    const names = readyQueue.slice(0, poolSize).map((t) => t.toolName);
    console.log(
      `\n  RUNNING ${poolSize} job(s) at the same time: ${names.join(', ')}`,
    );
    await Promise.all(Array.from({ length: poolSize }, () => runWorker()));
  }

  console.log(`\n${line}`);
  console.log(`  ALL DONE  --  ${completedSet.size} jobs completed`);
  console.log(`${line}\n`);

  return toolResults;
}

function buildHooks(): Hooks {
  const hooks = createHooks();

  addPreHook(hooks, async ({ tool }) => {
    if (tool.name === 'zsh') {
      let allowed = true;
      if ((tool.args.comand as string).includes('rm')) {
        allowed = await askPermission(tool.name, tool.args);
      }
      return allowed ? 'allow' : 'deny';
    }
    return 'allow';
  });

  addPostHook(hooks, ({ tool, result }) => {
    const res = result as { success?: boolean; errorMessage?: string };
    const ok = res?.success !== false;
    const icon = ok ? '✅' : '❌';
    const errSuffix =
      !ok && res?.errorMessage ? ` - Error: ${res.errorMessage}` : '';

    let details = '';
    if (tool.name === 'zsh') {
      details = ` [command: "${tool.args.comand}"]`;
    } else if (tool.name === 'file_write') {
      details = ` [file: ${tool.args.fileName}]`;
    } else if (tool.name === 'read_file') {
      details = ` [file: ${tool.args.fileName}]`;
    } else if (tool.name === 'grep_search') {
      details = ` [pattern: "${tool.args.pattern}" in ${tool.args.directory}]`;
    } else if (tool.name === 'find_files') {
      details = ` [pattern: "${tool.args.namePattern}" in ${tool.args.directory}]`;
    } else if (tool.name === 'git') {
      details = ` [git ${tool.args.gitCommand}]`;
    } else if (tool.name === 'create_a_subagent') {
      details = ` [query: "${tool.args.query}"]`;
    }

    console.log(`  ${icon}  ${tool.name}${details} done${errSuffix}`);
  });

  return hooks;
}

const SYSTEM_PROMPT = `
You are the Lead Coordinator Agent.
Your role is to understand the user's request, generate best-practice skills, and delegate all work to subagents.

MANDATORY — FOLLOW THIS ORDER:
1. Call 'skill_maker' FIRST. Write comprehensive best-practice guidance for the topic as the 'skills' argument (you write the content yourself). This will automatically be injected into every subagent you spawn.
2. Use 'read_file' if you need context from the project.
3. Delegate all actual work (file writes, shell commands, installs) using 'create_a_subagent'.
4. Do NOT write files or run commands yourself.

Subagents have access to: zsh, file_write, read_file, grep_search, find_files, git, plan_maker.

Guidelines:
- Divide complex tasks into clear sub-tasks, each handled by a separate subagent.
- Instruct subagents to use grep_search/find_files before writing code.
- Instruct subagents to commit with git after finishing.
`;

export const agentCommand = new Command('agent')
  .description('Runs the agent')
  .option('-p, --prompt <prompt>', 'prompt', '')
  .action(async (options) => {
    try {
      if (!options.prompt) return;

      const query: string = options.prompt;
      const hooks = buildHooks();


      console.log(`[QUERY_ASKED] ${query}\n`);

      let session;
      try {
        session = await getCurrentSession();
      } catch (error) {
        if (error instanceof Error && !session) {
          console.error(error.message);
        } else {
          console.error(String(error));
        }
        process.exit(1);
      }

      // google 
      if (
        session.provider === 'google' &&
        session.apiKey &&
        session.client instanceof GoogleGenAI
      ) {
        const tools = getAllToolsOfProviders(
          'google',
        )! as FunctionDeclaration[];

        const coordinatorTools = tools.filter(
          (t) =>
            t.name === 'create_a_subagent' ||
            t.name === 'read_file' ||
            t.name === 'plan_maker' ||
            t.name === 'skill_maker',
        );
        const chat = session.client.chats.create({
          model: session.model!,
          config: {
            systemInstruction: SYSTEM_PROMPT,
            tools: [{ functionDeclarations: coordinatorTools }],
          },
        });

        let response = await chat.sendMessage({ message: query });
        let tokenConsumed = 0;
        const toolResults: Part[] = [];
        while (response.functionCalls && response.functionCalls.length > 0) {
          const queue = [...response.functionCalls];
          
  
          async function runWorker(): Promise<void> {
            const tool = queue.shift();
            if (!tool) return;

            const result = await dispatchTool(
              tool.name!,
              tool.args as Record<string, unknown>,
              hooks,
            );

            if (tool.name === 'plan_maker') {
              const scheduledResults: Part[] = JSON.parse(result);
              toolResults.push(...scheduledResults);
            } else {
              toolResults.push({
                functionResponse: { name: tool.name!, response: { result } },
              });
            }

            return runWorker();
          }

          tokenConsumed+=response.usageMetadata?.totalTokenCount!;
          console.log("[TOKEN_CONSUMED`]",tokenConsumed)
          const poolSize = Math.min(queue.length, 5);
          await Promise.all(
            Array.from({ length: poolSize }, () => runWorker()),
          );

          response = await chat.sendMessage({ message: toolResults });
        }

        const summaryResponse = await chat.sendMessage({
          message: '(summarize what you did)',
        });
        console.log(`\n${summaryResponse.text ?? ''}`);

        //  OpenAI
      } else if (
        session.provider === 'openai' &&
        session.apiKey &&
        session.client instanceof OpenAI
      ) {
        console.log('enter in openai loop');

        const tools = getAllToolsOfProviders(
          'openai',
        )! as unknown as OpenAI.Chat.ChatCompletionTool[];
        const coordinatorTools = tools.filter(
          (t) =>
            t.type === 'function' &&
            (t.function.name === 'create_a_subagent' ||
              t.function.name === 'read_file' ||
              t.function.name === 'skill_maker'),
        );
        const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: query },
        ];

        let response = await session.client.chat.completions.create({
          model: session.model,
          messages,
          tools: coordinatorTools,
        });

        while (response.choices[0].finish_reason === 'tool_calls') {
          const assistantMsg = response.choices[0].message;
          messages.push(assistantMsg);

          for (const toolCall of assistantMsg.tool_calls!) {
            if (toolCall.type !== 'function') continue;

            const args = JSON.parse(toolCall.function.arguments) as Record<
              string,
              unknown
            >;
            const result = await dispatchTool(
              toolCall.function.name,
              args,
              hooks,
            );
            messages.push({
              role: 'tool',
              tool_call_id: toolCall.id,
              content: result,
            });
          }

          response = await session.client.chat.completions.create({
            model: session.model,
            messages,
            tools: coordinatorTools,
          });
        }

        console.log(response.choices[0].message.content);
      } else if (
        session.provider === 'claude' &&
        session.apiKey &&
        session.client instanceof Anthropic
      ) {
        const tools = getAllToolsOfProviders(
          'claude',
        )! as unknown as Anthropic.Tool[];
        const coordinatorTools = tools.filter(
          (t) => t.name === 'create_a_subagent' || t.name === 'read_file' || t.name === 'skill_maker',
        );
        const messages: Anthropic.MessageParam[] = [
          { role: 'user', content: query },
        ];

        let response = await session.client.messages.create({
          model: session.model,
          max_tokens: 4096,
          system: SYSTEM_PROMPT,
          messages,
          tools: coordinatorTools,
        });

        while (response.stop_reason === 'tool_use') {
          messages.push({ role: 'assistant', content: response.content });

          const toolResults: Anthropic.ToolResultBlockParam[] = [];
          for (const block of response.content) {
            if (block.type === 'tool_use') {
              const result = await dispatchTool(
                block.name,
                block.input as Record<string, unknown>,
                hooks,
              );
              toolResults.push({
                type: 'tool_result',
                tool_use_id: block.id,
                content: result,
              });
            }
          }
          messages.push({ role: 'user', content: toolResults });

          response = await session.client.messages.create({
            model: session.model,
            max_tokens: 4096,
            system: SYSTEM_PROMPT,
            messages,
            tools: coordinatorTools,
          });
        }

        const textBlock = response.content.find((b) => b.type === 'text');
        if (textBlock && textBlock.type === 'text') {
          console.log(textBlock.text);
        }
      }
    } catch (e) {
      if (e instanceof Error) {
        const apiErr = e as Error & { status?: number };
        if (apiErr.status) {
          console.error(`\n  ERROR ${apiErr.status}: ${apiErr.message}\n`);
        } else {
          console.error(`\n  ERROR: ${apiErr.message}\n`);
        }
      } else {
        console.error(`\n  ERROR: ${String(e)}\n`);
      }
    }
  });
